name: Changelog and Tag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Build tag (eg. 2021-07-01-2)"
        required: true
  schedule:
    - cron: "0 4 * * *"
jobs:
  changelog-and-tag:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
          fetch-depth: 0
      -
        name: Compute tag
        id: tag
        run: |
          build_tag="${{ github.event.inputs.tag }}"
          [[ -z "$build_tag" ]] && build_tag="$(date +'%Y-%m-%d')"
          echo "::set-output name=tag::$build_tag"
      -
        name: Update and tag
        uses: ./.github/actions/changelog-and-tag
        with:
          tag: ${{ steps.tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
