name: Changelog and Tag
on:
  schedule:
    - cron: "0 4 * * *"
jobs:
  changelog-and-tag:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
          fetch-depth: 0
      -
        name: Compute tag
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Update and tag
        uses: ./.github/actions/changelog-and-tag
        with:
          tag: ${{ steps.date.outputs.date }}
