# Copyright 2022 MobiledgeX, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Push API docs to api-docs repo
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Build tag for edge-cloud image to pull API docs from (eg. 2021-07-01-2)"
        required: true
        default: "latest"
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed
env:
  REGISTRY: harbor.mobiledgex.net

jobs:

  push-api-docs:
    name: Push API docs
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        component: [ client, mc ]

    steps:
      -
        name: Check out the api-docs repo
        uses: actions/checkout@v2
        with:
          repository: mobiledgex-docs/api-docs-${{ matrix.component }}
          token: ${{ secrets.PAT }}
          path: api-docs
      -
        name: Log in to docker
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Dump API docs
        id: dump-docs
        run: |
          build_tag="${{ github.event.inputs.tag }}"
          [[ -z "$build_tag" ]] && build_tag="latest"
          docker run --rm "${REGISTRY}/mobiledgex/edge-cloud:${build_tag}" dump-docs ${{ matrix.component }} >"api-docs/swagger.json"
          version=$( docker run --rm "${REGISTRY}/mobiledgex/edge-cloud:${build_tag}" version )
          echo "::set-output name=version::$version"
      -
        name: Commit changes
        run: |
          cd api-docs
          if git diff --exit-code --quiet; then
            echo "::notice title=No changes::No API docs changes since the last update"
            exit 0
          fi
          git config --global user.name github
          git config --global user.email "Github Actions <mobiledgex.ops@mobiledgex.com>"
          git add .
          git commit -m "${{ steps.dump-docs.outputs.version }}"
          git push
